# Application: Singular
# Project: PM Automation
# Author: Salvador Soto
"""
scripts/uat_09_process_pm_report_decisions.py
=============================================
Phase 11b+ — Process returned pm_report chunks with steward decisions.

Reads pm_report Excel files (generated by uat_08_generate_pm_reports.py,
returned by stewards with DSR_DECISION filled) from uat/non_uat_decisions/,
extracts decisions, scores pairs with the frozen RF model, deduplicates against
existing blind_uat and blind_non_uat results, and writes to results_non_uat/.

Governance (ARCHITECTURE.md v2.7.2):
  RULE-002  blind_non_uat source — eligible for CI when blindness verified
  RULE-006  generation_date, model_version, source, phase in all outputs
  RULE-011  Predictor public interface only (RULE-011)
  RULE-012  Decisions normalized via normalize_target() (FAILURE-004 prevention)
  KNOWN-DEVIATION-003  RESOLVED 2026-09-15 — anti-join now queries
                       PairRegistry.get_resolved_pairs() first, CSV read kept as a
                       fallback/safety net for historical data recorded before this change.

Reclassification policy: pm_report chunks qualify as blind_non_uat when:
  (1) No model-output columns present (blindness check passes)
  (2) Stewards reviewed without seeing model scores (uat_08 blind mode)
  (3) uat_06 deduplication enforces blind_uat > blind_non_uat priority
  Documented: ARCHITECTURE.md v2.7.2 Source Type Classification.

File pattern recognised: {ISO}_{YYYYMMDD}_{HHMM}_set{N}[-SharePoint_suffix].xlsx
SharePoint suffixes stripped before grouping: e.g. set01-EMAAPhCk0Gb1fHy → set01.

Usage
-----
  python scripts/uat_09_process_pm_report_decisions.py
  python scripts/uat_09_process_pm_report_decisions.py --countries DE HK
  python scripts/uat_09_process_pm_report_decisions.py --dry-run
  python scripts/uat_09_process_pm_report_decisions.py --input-dir uat/non_uat_decisions
"""

from __future__ import annotations

import argparse
import hashlib
import logging
import math
import re
import sys
import tempfile
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Dict, List, Set, Tuple

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s – %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger("uat_09_pm_decisions")

# ---------------------------------------------------------------------------
# Canonical paths (ARCHITECTURE.md v2.7.2)
# ---------------------------------------------------------------------------
UAT_DIR = ROOT / "uat"
NON_UAT_DECISIONS_DIR = UAT_DIR / "non_uat_decisions"
RESULTS_DIR = UAT_DIR / "results"  # blind_uat results (KNOWN-DEVIATION-003)
RESULTS_NON_UAT_DIR = UAT_DIR / "results_non_uat"
MODELS_DIR = ROOT / "models"
PASO_6_PATH = MODELS_DIR / "paso_6_model_strategy_decision.json"
# Reconciliation waterfall (Phase 1 of the 2026-09-15 UAT methodology audit plan) —
# one row per (market, file-group) run, appended, never overwritten (RULE-002 evidence trail).
WATERFALL_PATH = UAT_DIR / "manifest" / "reconciliation_waterfall.csv"

SOURCE = "blind_non_uat"
PHASE = "11b"

# PM_REPORT_PATTERN: matches files generated by uat_08 that stewards have returned.
# Snowflake MDM extracts (matched by uat_05) are NOT matched by this pattern.
# Optional "PM_HCP_" prefix covers the naming convention introduced in ARCHITECTURE v2.7.3
# (Decile-Aware Predict Reveal, 2026-09-02) alongside the legacy "{CC}_..." naming (FAILURE-018).
# Medconnect batches (uat_14) use PM_HCP_{CC}_MEDCONNECT_{AUTOMATED|MANUAL}_{ts}.xlsx with no _set
# suffix; the lookahead keeps _set mandatory for every other name. Groups 1/2 stay (iso, ts).
PM_REPORT_RE = re.compile(
    r"^(?=(?:PM_HCP_)?[A-Z]{2}_MEDCONNECT_|.*_set\d{2,3}(?:-[A-Za-z0-9]+)?$)"
    r"(?:PM_HCP_)?([A-Z]{2})_(?:MEDCONNECT_(?:AUTOMATED|MANUAL)_)?(\d{8}_\d{4})"
    r"(?:_set(\d{2,3}))?(?:-[A-Za-z0-9]+)?$"
)
# Strip SharePoint download suffixes: set01-EMAAPhCk0Gb1fHy → set01
_SP_SUFFIX_RE = re.compile(r"-[A-Za-z0-9]{12,}$")

# Markets eligible for pm_report decision extraction
# AR/BR/MX/CA added (2026-09-21): uat_08 was run with --no-exclude-latam to extend the
# Decile-Aware Predict Reveal pm_report cycle to these AMER markets; this script was not
# updated at the time, so returned chunks for them were silently skipped (0 groups matched).
# HN/DO/CR/NI/CO/PE/CL added (2026-09-23): occurrence #3 of the same FAILURE-018 root cause
# (uat_08 market coverage outpaces this allowlist) — see KNOWN_FAILURES.md FAILURE-018
# recurrence addendum and BACKLOG-009 for the pending structural fix.
ELIGIBLE_ISO: Set[str] = {
    "DE",
    "FR",
    "HK",
    "IN",
    "PH",
    "TH",
    "TR",
    "RU",
    "IT",
    "PK",
    "ID",
    "MY",
    "AR",
    "BR",
    "MX",
    "CA",
    "HN",
    "DO",
    "CR",
    "NI",
    "CO",
    "PE",
    "CL",
    "EC",
    "UY",
    # 2026-10-01: returned GT/EG files were skipped silently (FAILURE-018, 4th occurrence)
    "GT",
    "EG",
}

ISO_TO_SLUG: Dict[str, str] = {
    "DE": "germany",
    "FR": "france",
    "HK": "hong_kong",
    "IN": "india",
    "PH": "philippines",
    "TH": "thailand",
    "TR": "turkey",
    "RU": "russia",
    "IT": "italy",
    "PK": "pakistan",
    "ID": "indonesia",
    "MY": "malaysia",
    "AR": "argentina",
    "BR": "brazil",
    "MX": "mexico",
    "CA": "canada",
    "HN": "honduras",
    "DO": "dominican_republic",
    "CR": "costa_rica",
    "NI": "nicaragua",
    "CO": "colombia",
    "PE": "peru",
    "CL": "chile",
    # 2026-09-23 — registered atomically with uat_08's ISO_TO_SLUG (FAILURE-018 prevention)
    "EC": "ecuador",
    "UY": "uruguay",
    "GT": "guatemala",
    "EG": "egypt",
}

# Blindness violation patterns — same as uat_05 (RULE-002)
BLINDNESS_VIOLATION_PATTERNS = [
    "prob_merge",
    "probability",
    "prediction",
    "predicted",
    "confidence",
    "conf_",
    "score_bucket",
    "score_interval",
    "model_decision",
    "auto_",
    "prob_",
]

# Genuine independent Data Steward decision column (FAILURE-019 fix). DSR_DECISION is only
# the Decile-Aware Predict Reveal pre-fill target (Y/N/S) — used as a fallback exclusively
# for legacy pm_report files (pre-v2.7.3) that never had this column.
SYSTEM_LABEL_COL = "MERGE / NO MERGE / SUSPECT"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _load_paso6() -> Dict:
    import json

    with open(PASO_6_PATH, encoding="utf-8") as fh:
        raw = json.load(fh)
    return raw.get("decision", {}).get("by_country", {})


def _sha256_file(path: Path) -> str:
    """Content hash of a model file — the true model-version identity (Phase 3)."""
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for block in iter(lambda: fh.read(65536), b""):
            h.update(block)
    return h.hexdigest()


def _check_blindness(df: pd.DataFrame, slug: str) -> None:
    """Raise if any model-output column is detected (RULE-002 enforcement).

    FAILURE-018 fix: files carrying a `DECISION_SOURCE` column went through the
    Decile-Aware Predict Reveal mechanism (ARCHITECTURE v2.7.3) and are sanctioned to
    carry model-output columns (PROB_MERGE/PROB_NO_MERGE/PREDICTION/CONFIDENCE_LEVEL/
    SCORE_BUCKET/AUTOMATION_STATUS, plus adjacent APMU confidence fields) even when
    blank for non-revealed rows. `DECISION_SOURCE` is the unambiguous signature of that
    mechanism — its presence is checked instead of the market's *current* automation
    approval status, which can change between file generation and processing (a market
    approved when the file was generated may since have been reverted to MANUAL with
    more evidence, without the already-generated file's columns becoming a violation
    retroactively). An exact-column allowlist was tried first and abandoned: legitimate
    pre-existing business columns (e.g. apmu_decision_confidence) also match the
    violation patterns, making an allowlist fragile and incomplete in practice.
    """
    if "DECISION_SOURCE" in df.columns:
        logger.info(
            "  [%s] Blindness check skipped — file carries DECISION_SOURCE "
            "(Decile-Aware Predict Reveal, FAILURE-018)",
            slug,
        )
        return
    cols_lower = {c.lower() for c in df.columns}
    violations = [
        pat
        for pat in BLINDNESS_VIOLATION_PATTERNS
        if any(c.startswith(pat) or pat in c for c in cols_lower)
    ]
    if violations:
        raise ValueError(
            f"[{slug}] BLINDNESS VIOLATION in pm_report chunk: {violations}. "
            f"File likely contains model output. Not eligible as blind_non_uat."
        )


def _normalize_decision(series: pd.Series) -> pd.Series:
    """Normalize DSR_DECISION to binary via canonical normalize_target() (RULE-012 / FAILURE-004).

    Pre-processes MDM-specific synonyms not covered by normalize_target():
    'Match'/'match' → 'Merge' (some stewards use this term interchangeably).
    """
    from src.reporting.error_analysis import normalize_target

    # Map MDM synonym before canonical normalization
    cleaned = series.astype(str).str.strip().str.replace(r"^[Mm]atch$", "Merge", regex=True)
    return normalize_target(cleaned)


def _assign_score_bucket(prob: float) -> str:
    b = min(int(math.floor(prob * 10)), 9)
    return f"{b / 10:.1f}–{(b + 1) / 10:.1f}"


def _load_resolved_pair_ids(slug: str) -> Set[str]:
    """
    Load pair_ids already resolved in blind_uat or prior blind_non_uat results.

    KNOWN-DEVIATION-003 RESOLVED: queries PairRegistry.get_resolved_pairs() first
    (populated going forward by uat_00 for blind_uat and by this script for
    blind_non_uat — see the record_steward_review() call in process_market()).
    The direct CSV read is kept as a union, not replaced, because pairs resolved
    before this change was deployed are not retroactively present in the registry.
    """
    resolved: Set[str] = set()
    try:
        from src.lineage.pair_registry import PairRegistry

        registry = PairRegistry(ROOT / "data" / "lineage")
        resolved |= set(registry.get_resolved_pairs(slug))
        logger.info("  [%s] Loaded %d resolved pair_ids from PairRegistry", slug, len(resolved))
    except Exception as exc:
        logger.warning("  [%s] PairRegistry.get_resolved_pairs lookup skipped: %s", slug, exc)
    for results_path in [
        RESULTS_DIR / f"{slug}_steward_results.csv",
        RESULTS_NON_UAT_DIR / f"{slug}_non_uat_results.csv",
    ]:
        if results_path.exists():
            df_r = pd.read_csv(results_path)
            if "pair_id" in df_r.columns:
                resolved |= set(df_r["pair_id"].dropna().astype(str))
                logger.info(
                    "  [%s] Loaded %d resolved pair_ids from %s",
                    slug,
                    len(df_r),
                    results_path.name,
                )
    return resolved


def _append_waterfall_record(record: Dict) -> None:
    """Append one reconciliation-waterfall row (Phase 1, 2026-09-15 UAT methodology audit).

    Never overwrites — this is an evidence trail, not a cache. Safe to call repeatedly;
    each (market, file-group) run adds one row, timestamped, so re-processing history is
    preserved rather than replaced (mirrors the append-only convention of results_non_uat CSVs).
    """
    try:
        WATERFALL_PATH.parent.mkdir(parents=True, exist_ok=True)
        row = pd.DataFrame([record])
        if WATERFALL_PATH.exists():
            existing = pd.read_csv(WATERFALL_PATH)
            combined = pd.concat([existing, row], ignore_index=True)
        else:
            combined = row
        combined.to_csv(WATERFALL_PATH, index=False, encoding="utf-8")
    except Exception as exc:
        logger.warning(
            "  [%s] Reconciliation waterfall record skipped: %s", record.get("country"), exc
        )


def _discover_pm_report_files(
    input_dir: Path,
) -> Dict[Tuple[str, str], List[Path]]:
    """
    Discover pm_report chunk files and group by (iso, timestamp).
    Returns {(iso, timestamp): [sorted paths]}.
    """
    groups: Dict[Tuple[str, str], List[Path]] = {}
    for p in sorted(input_dir.glob("*.xlsx")):
        # Normalise SharePoint suffix from stem before matching
        stem_clean = _SP_SUFFIX_RE.sub("", p.stem)
        # Strip optional "reviewed_" prefix stewards add when returning files (same convention
        # already handled in uat_00_prepare_steward_results.py via removeprefix("reviewed_")).
        stem_clean = re.sub(r"^reviewed_", "", stem_clean, flags=re.IGNORECASE)
        m = PM_REPORT_RE.match(stem_clean)
        if not m:
            continue
        iso = m.group(1)
        ts = m.group(2)
        if iso not in ELIGIBLE_ISO:
            continue
        key = (iso, ts)
        groups.setdefault(key, []).append(p)
    return groups


def _commit_pending_file_success(registry, pending: List[Tuple[str, Dict]]) -> None:
    """Commit queued file-registry SUCCESS results — only call once the (iso, ts) group has
    durably reached a safe terminal state (IMPLEMENTATION_REVIEW finding F1). If the group
    aborts before this is called (e.g. an exception raised earlier in the loop), the queued
    entries are simply never committed and stay at their pre-existing RUNNING/FAILED status,
    so the next run will correctly retry those files instead of silently skipping them."""
    if registry is None:
        return
    for file_hash, result in pending:
        registry.record_ingested_file_result(file_hash, {**result, "status": "SUCCESS"})


# ---------------------------------------------------------------------------
# Per-market scoring + preparation
# ---------------------------------------------------------------------------


def process_market(
    iso: str,
    ts: str,
    chunk_paths: List[Path],
    paso6: Dict,
    dry_run: bool,
) -> None:
    slug = ISO_TO_SLUG[iso]
    logger.info("[%s] Processing %d chunk(s) (ts=%s)", slug, len(chunk_paths), ts)

    # Operational PM Reports Slice: INGESTED_FILE_REGISTRY hash-based idempotency
    # (dataiku_migration/design/recipe_ingest_steward_decisions.design.md)
    ingestion_run_id = f"{slug}_nonuat_{ts}"
    try:
        from src.lineage.pair_registry import PairRegistry

        registry = PairRegistry(ROOT / "data" / "lineage")
    except Exception as _exc:
        logger.warning("[%s] PairRegistry unavailable for file-registry tracking: %s", slug, _exc)
        registry = None

    # Aggregate DSR_DECISION from all sets
    decision_frames: List[pd.DataFrame] = []
    raw_frames: List[pd.DataFrame] = []
    # (file_hash, result_dict) pairs — SUCCESS is only committed once the whole (iso, ts) group
    # durably completes (IMPLEMENTATION_REVIEW finding F1); never mark a file SUCCESS while a
    # later file in the same group could still fail and abort the group's write.
    pending_file_success: List[Tuple[str, Dict]] = []

    # Reconciliation waterfall counters (Phase 1, 2026-09-15 UAT methodology audit plan)
    files_discovered = len(chunk_paths)
    files_processed = 0
    files_already_processed = 0
    raw_rows_total = 0
    rows_with_decision_total = 0
    automated_excluded_total = 0
    independently_reviewed_total = 0

    for path in sorted(chunk_paths):
        logger.info("  [%s] Reading: %s", slug, path.name)

        file_hash = None
        if registry is not None and not dry_run:
            try:
                file_hash = _sha256_file(path)
                existing_entry = registry.get_file_registry_entry(file_hash)
                if existing_entry and existing_entry.get("status") == "SUCCESS":
                    logger.info(
                        "  [%s] Skipping %s — already ingested (hash=%s, matches %s)",
                        slug,
                        path.name,
                        file_hash[:12],
                        existing_entry.get("file_name"),
                    )
                    files_already_processed += 1
                    continue
                registry.record_ingested_file_start(
                    file_hash=file_hash,
                    file_name=path.name,
                    file_path=str(path),
                    market_iso=iso,
                    ingestion_run_id=ingestion_run_id,
                )
            except Exception as _exc:
                logger.warning(
                    "  [%s] File-registry hash check skipped for %s: %s", slug, path.name, _exc
                )

        try:
            df_chunk = pd.read_excel(
                path, sheet_name=0, engine="openpyxl"
            )  # stewards rename PM_Records to Sheet1 on save
        except Exception as exc:
            logger.warning("  [%s] Cannot read PM_Records from %s: %s", slug, path.name, exc)
            if registry is not None and file_hash:
                registry.record_ingested_file_result(
                    file_hash, {"status": "FAILED", "error_message": str(exc)}
                )
            continue

        # Blindness check (RULE-002)
        try:
            _check_blindness(df_chunk, slug)
        except Exception as exc:
            if registry is not None and file_hash:
                registry.record_ingested_file_result(
                    file_hash,
                    {"status": "FAILED", "error_message": str(exc), "raw_rows": len(df_chunk)},
                )
            raise

        if "pair_id" not in df_chunk.columns:
            logger.warning("  [%s] pair_id column missing in %s — skipping", slug, path.name)
            if registry is not None and file_hash:
                registry.record_ingested_file_result(
                    file_hash,
                    {
                        "status": "FAILED",
                        "error_message": "pair_id column missing",
                        "raw_rows": len(df_chunk),
                    },
                )
            continue

        # FAILURE-019 fix: prefer the genuine steward decision column; DSR_DECISION alone
        # (used by legacy pre-v2.7.3 files) is the fallback when the newer column is absent.
        if SYSTEM_LABEL_COL in df_chunk.columns:
            resolved_decision = df_chunk[SYSTEM_LABEL_COL]
        elif "DSR_DECISION" in df_chunk.columns:
            resolved_decision = df_chunk["DSR_DECISION"]
        else:
            logger.warning(
                "  [%s] Neither '%s' nor 'DSR_DECISION' present in %s — skipping",
                slug,
                SYSTEM_LABEL_COL,
                path.name,
            )
            if registry is not None and file_hash:
                registry.record_ingested_file_result(
                    file_hash,
                    {
                        "status": "FAILED",
                        "error_message": "no decision column present",
                        "raw_rows": len(df_chunk),
                    },
                )
            continue

        # RULE-026 traceability: track whether this row's decision came from the genuine
        # steward column (HUMAN) or the legacy DSR_DECISION-only fallback (LEGACY_DSR_FALLBACK)
        review_source_value = (
            "HUMAN" if SYSTEM_LABEL_COL in df_chunk.columns else "LEGACY_DSR_FALLBACK"
        )

        df_chunk = df_chunk.copy()
        df_chunk["_resolved_decision"] = resolved_decision
        df_chunk["_review_source"] = review_source_value

        # Keep only rows with a filled decision
        filled = df_chunk[
            df_chunk["_resolved_decision"].notna()
            & (df_chunk["_resolved_decision"].astype(str).str.strip() != "")
        ].copy()

        # FAILURE-019 circularity guard: an AUTOMATED passthrough is not an independent
        # human review, regardless of which column it landed in — exclude unconditionally.
        if "DECISION_SOURCE" in filled.columns:
            n_before_auto_filter = len(filled)
            filled = filled[filled["DECISION_SOURCE"] != "AUTOMATED"]
            n_automated_excluded = n_before_auto_filter - len(filled)
        else:
            n_before_auto_filter = len(filled)
            n_automated_excluded = 0

        logger.info(
            "  [%s] %s: %d rows, %d independently-reviewed decisions (%d AUTOMATED excluded)",
            slug,
            path.name,
            len(df_chunk),
            len(filled),
            n_automated_excluded,
        )

        files_processed += 1
        raw_rows_total += len(df_chunk)
        rows_with_decision_total += n_before_auto_filter
        automated_excluded_total += n_automated_excluded
        independently_reviewed_total += len(filled)

        if registry is not None and file_hash:
            # Group-level dedup/anti-join/conflict counts (duplicates_within_file,
            # duplicates_across_files, already_resolved, new_resolved_pairs, conflicting_decisions)
            # are only knowable after aggregating this whole (iso, ts) group — they are captured
            # in RECONCILIATION_WATERFALL below, not here (INGESTED_FILE_REGISTRY.schema.yaml
            # documents these fields as group-level-only; they remain 0 at the per-file grain).
            # SUCCESS itself is NOT committed here — only queued — until the group durably
            # completes (see pending_file_success commit points below; F1 fix).
            pending_file_success.append(
                (
                    file_hash,
                    {
                        "raw_rows": len(df_chunk),
                        "rows_with_decision": n_before_auto_filter,
                        "automated_rows_excluded": n_automated_excluded,
                    },
                )
            )

        decision_frames.append(
            filled[["pair_id", "_resolved_decision", "_review_source"]].rename(
                columns={"_resolved_decision": "DSR_DECISION"}
            )
        )
        # Keep all columns for scoring (drop decision/source columns so Predictor won't reject them)
        raw_frames.append(
            filled.drop(
                columns=["_resolved_decision", "DSR_DECISION", SYSTEM_LABEL_COL, "_review_source"],
                errors="ignore",
            )
        )

    if not decision_frames:
        logger.warning("[%s] No filled decisions found across all chunks", slug)
        if not dry_run:
            _commit_pending_file_success(registry, pending_file_success)
            _append_waterfall_record(
                {
                    "run_timestamp": datetime.now(timezone.utc).isoformat(),
                    "country": slug,
                    "iso": iso,
                    "file_group_ts": ts,
                    "source_type": SOURCE,
                    "files_discovered": files_discovered,
                    "files_processed": files_processed,
                    "files_already_processed": files_already_processed,
                    "files_skipped": files_discovered - files_processed - files_already_processed,
                    "raw_rows": raw_rows_total,
                    "rows_with_decision": 0,
                    "automated_prefill_excluded": 0,
                    "independently_reviewed_rows": 0,
                    "duplicate_rows_removed_at_aggregation": 0,
                    "already_resolved_removed": 0,
                    "eligible_evidence_rows": 0,
                    "exclusion_reason": "no_filled_decisions_in_any_chunk",
                }
            )
        return

    # Concatenate and dedup by pair_id (keep first occurrence across sets — combines
    # within-file and cross-file duplicates; not split further, documented limitation)
    decisions_df = pd.concat(decision_frames, ignore_index=True)
    rows_before_dedup = len(decisions_df)
    decisions_df = decisions_df.drop_duplicates(subset=["pair_id"], keep="first")
    duplicate_rows_removed = rows_before_dedup - len(decisions_df)
    raw_df = pd.concat(raw_frames, ignore_index=True).drop_duplicates(
        subset=["pair_id"], keep="first"
    )
    logger.info("[%s] Aggregated: %d unique pair_ids with decisions", slug, len(decisions_df))

    # Anti-join: remove pairs already resolved in blind_uat or prior blind_non_uat
    resolved_ids = _load_resolved_pair_ids(slug)
    before = len(decisions_df)
    decisions_df = decisions_df[~decisions_df["pair_id"].isin(resolved_ids)]
    raw_df = raw_df[raw_df["pair_id"].isin(decisions_df["pair_id"])]
    already_resolved_removed = before - len(decisions_df)
    logger.info(
        "[%s] After anti-join: %d new pair_ids (%d removed)",
        slug,
        len(decisions_df),
        already_resolved_removed,
    )

    if len(decisions_df) == 0:
        logger.info("[%s] All pairs already resolved — nothing to write", slug)
        if not dry_run:
            _commit_pending_file_success(registry, pending_file_success)
            _append_waterfall_record(
                {
                    "run_timestamp": datetime.now(timezone.utc).isoformat(),
                    "country": slug,
                    "iso": iso,
                    "file_group_ts": ts,
                    "source_type": SOURCE,
                    "files_discovered": files_discovered,
                    "files_processed": files_processed,
                    "files_already_processed": files_already_processed,
                    "files_skipped": files_discovered - files_processed - files_already_processed,
                    "raw_rows": raw_rows_total,
                    "rows_with_decision": rows_with_decision_total,
                    "automated_prefill_excluded": automated_excluded_total,
                    "independently_reviewed_rows": independently_reviewed_total,
                    "duplicate_rows_removed_at_aggregation": duplicate_rows_removed,
                    "already_resolved_removed": already_resolved_removed,
                    "eligible_evidence_rows": 0,
                    "exclusion_reason": "all_pairs_already_resolved",
                }
            )
        return

    # Normalize decisions via canonical normalize_target() (RULE-012 / FAILURE-004)
    # Pre-normalize variant spellings not covered by normalize_target ('Match' = Merge synonym)
    _DSR_ALIASES = {"match": "Merge", "matched": "Merge", "no match": "No Merge"}
    decisions_df = decisions_df.copy()
    decisions_df["DSR_DECISION"] = (
        decisions_df["DSR_DECISION"]
        .astype(str)
        .str.strip()
        .apply(lambda v: _DSR_ALIASES.get(v.lower(), v))
    )
    decisions_df["steward_label"] = _normalize_decision(decisions_df["DSR_DECISION"])
    decisions_df["steward_decision"] = decisions_df["DSR_DECISION"]

    # Score with frozen RF model via Predictor (RULE-011)
    entry = paso6.get(slug, {})
    decision_strategy = entry.get("decision", "GLOBAL")
    threshold = float(entry.get("threshold_optimal", {}).get("threshold_merge", 0.5))

    strategy_lower = decision_strategy.lower()
    if strategy_lower == "evaluate":
        custom_path = MODELS_DIR / f"model_custom_{slug}.pkl"
        strategy_lower = "custom" if custom_path.exists() else "global"

    model_file = f"model_custom_{slug}.pkl" if strategy_lower == "custom" else "model_global.pkl"
    model_path = MODELS_DIR / model_file
    model_version = model_path.name if model_path.exists() else "global_fallback"
    # Phase 3 (model-version evidence segregation): filename alone doesn't change across
    # retrains, so also capture the content hash — the true "materially different model"
    # identity used by uat_04/uat_06's drift guard (_check_model_drift).
    model_file_sha256 = _sha256_file(model_path) if model_path.exists() else None

    if slug not in paso6:
        logger.warning(
            "[%s] Not registered in paso_6_model_strategy_decision.json — "
            "using GLOBAL model as fallback (RULE-017)",
            slug,
        )

    logger.info(
        "[%s] Scoring — strategy=%s threshold=%.3f model=%s",
        slug,
        strategy_lower,
        threshold,
        model_file,
    )

    if dry_run:
        raw_df["prob_merge"] = np.random.default_rng(42).uniform(0, 1, len(raw_df))
        raw_df["predicted_class"] = (raw_df["prob_merge"] >= threshold).map(
            {True: "MERGE", False: "NO_MERGE"}
        )
    else:
        from src.inference.predictor import Predictor

        predictor = Predictor(
            base_dir=ROOT,
            strategy=strategy_lower,
            enable_rules=False,
            enable_tree_explainability_metrics=False,
        )

        with tempfile.TemporaryDirectory() as tmpdir:
            tmp_path = Path(tmpdir) / f"{slug}_score_input.xlsx"
            raw_df.to_excel(tmp_path, index=False, engine="openpyxl")
            output_df, _ = predictor.predict(input_path=tmp_path, country=slug)

        if output_df is None or len(output_df) == 0:
            raise RuntimeError(f"[{slug}] Predictor returned empty output")

        prob_col = next(
            (
                c
                for c in output_df.columns
                if "probability" in c.lower() or "prob_merge" in c.lower()
            ),
            None,
        )
        pred_col = next(
            (c for c in output_df.columns if "prediction" in c.lower() or "predicted" in c.lower()),
            None,
        )
        if prob_col is None or pred_col is None:
            raise RuntimeError(
                f"[{slug}] Cannot locate probability/prediction columns: {list(output_df.columns)}"
            )

        raw_df = raw_df.copy()
        raw_df["prob_merge"] = output_df[prob_col].values
        raw_df["predicted_class"] = output_df[pred_col].values

    raw_df["score_bucket"] = raw_df["prob_merge"].clip(0.0, 1.0).apply(_assign_score_bucket)

    # Preserve original DECISION_SOURCE from the reveal mechanism (FAILURE-018 fix) —
    # lets downstream consumers (uat_10 evidence report) exclude AUTOMATED passthrough
    # rows from independent-review metrics. Blank when the market has no reveal active.
    if "DECISION_SOURCE" in raw_df.columns:
        raw_df["decision_source"] = raw_df["DECISION_SOURCE"].fillna("")
    else:
        raw_df["decision_source"] = ""

    # Join scores back to decisions
    scored = decisions_df.merge(
        raw_df[["pair_id", "prob_merge", "predicted_class", "score_bucket", "decision_source"]],
        on="pair_id",
        how="left",
    )

    # Build output
    df_out = scored[
        [
            "pair_id",
            "steward_decision",
            "steward_label",
            "prob_merge",
            "predicted_class",
            "score_bucket",
            "decision_source",
        ]
    ].copy()
    df_out["source"] = SOURCE
    df_out["phase"] = PHASE
    df_out["model_version"] = model_version
    df_out["model_file_sha256"] = model_file_sha256
    df_out["generation_date"] = date.today().isoformat()
    df_out["country"] = slug

    n_merge = int((df_out["steward_label"] == 1).sum())
    n_no_merge = int((df_out["steward_label"] == 0).sum())
    logger.info(
        "[%s] Ready: %d records (MERGE=%d, NO_MERGE=%d)", slug, len(df_out), n_merge, n_no_merge
    )

    if dry_run:
        logger.info("[%s] [dry-run] output write skipped", slug)
        return

    RESULTS_NON_UAT_DIR.mkdir(parents=True, exist_ok=True)
    out_path = RESULTS_NON_UAT_DIR / f"{slug}_non_uat_results.csv"

    # Append to existing file (preserves prior entries from uat_05 or previous uat_09 runs)
    if out_path.exists():
        existing = pd.read_csv(out_path)
        combined = pd.concat([existing, df_out], ignore_index=True).drop_duplicates(
            subset=["pair_id"], keep="first"
        )
        combined.to_csv(out_path, index=False, encoding="utf-8")
        logger.info(
            "[%s] Appended to %s (%d existing + %d new = %d total)",
            slug,
            out_path.name,
            len(existing),
            len(df_out),
            len(combined),
        )
    else:
        df_out.to_csv(out_path, index=False, encoding="utf-8")
        logger.info("[%s] Written: %s (%d rows)", slug, out_path.name, len(df_out))

    # Lineage: record these as independently-reviewed steward decisions (KNOWN-DEVIATION-003
    # resolution) so future runs' _load_resolved_pair_ids() can find them via the registry.
    try:
        if registry is None:
            from src.lineage.pair_registry import PairRegistry

            registry = PairRegistry(ROOT / "data" / "lineage")
        registry.record_steward_review(
            df_out, uat_run_id=f"{slug}_nonuat_{ts}", decision_source=scored["_review_source"]
        )
    except Exception as _exc:
        logger.warning("[%s] Lineage record_steward_review skipped: %s", slug, _exc)

    # F1 fix: only now — after the results CSV is durably written and steward-review recording
    # has been attempted — commit the queued file-registry SUCCESS entries for this group.
    _commit_pending_file_success(registry, pending_file_success)

    _append_waterfall_record(
        {
            "run_timestamp": datetime.now(timezone.utc).isoformat(),
            "country": slug,
            "iso": iso,
            "file_group_ts": ts,
            "source_type": SOURCE,
            "files_discovered": files_discovered,
            "files_processed": files_processed,
            "files_already_processed": files_already_processed,
            "files_skipped": files_discovered - files_processed - files_already_processed,
            "raw_rows": raw_rows_total,
            "rows_with_decision": rows_with_decision_total,
            "automated_prefill_excluded": automated_excluded_total,
            "independently_reviewed_rows": independently_reviewed_total,
            "duplicate_rows_removed_at_aggregation": duplicate_rows_removed,
            "already_resolved_removed": already_resolved_removed,
            "eligible_evidence_rows": len(df_out),
            "exclusion_reason": "",
        }
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    global RESULTS_DIR, RESULTS_NON_UAT_DIR, MODELS_DIR, PASO_6_PATH, WATERFALL_PATH
    parser = argparse.ArgumentParser(
        description="Phase 11b+ — Process returned pm_report chunks with steward decisions"
    )
    parser.add_argument(
        "--input-dir",
        default=None,
        help="Input directory (default: uat/non_uat_decisions/)",
    )
    parser.add_argument(
        "--countries",
        nargs="*",
        default=None,
        help="ISO codes to process (e.g. DE HK TR). Default: all eligible.",
    )
    parser.add_argument("--dry-run", action="store_true")
    # Path overrides for Dataiku managed folder compatibility (P0.3)
    parser.add_argument(
        "--results-dir",
        default=None,
        help="Override blind_uat results dir (default: uat/results/)",
    )
    parser.add_argument(
        "--results-non-uat-dir",
        default=None,
        help="Override non-UAT results dir (default: uat/results_non_uat/)",
    )
    parser.add_argument("--models-dir", default=None, help="Override models dir (default: models/)")
    parser.add_argument(
        "--manifest-dir",
        default=None,
        help="Override manifest dir, for the reconciliation waterfall CSV (default: uat/manifest/)",
    )
    args = parser.parse_args()

    # Reassign module-level path constants in place so every existing helper
    # (which reads these as bare globals) transparently picks up the override.
    if args.results_dir:
        RESULTS_DIR = Path(args.results_dir)
    if args.results_non_uat_dir:
        RESULTS_NON_UAT_DIR = Path(args.results_non_uat_dir)
    if args.models_dir:
        MODELS_DIR = Path(args.models_dir)
        PASO_6_PATH = MODELS_DIR / "paso_6_model_strategy_decision.json"
    if args.manifest_dir:
        WATERFALL_PATH = Path(args.manifest_dir) / "reconciliation_waterfall.csv"

    input_dir = Path(args.input_dir) if args.input_dir else NON_UAT_DECISIONS_DIR
    if not input_dir.exists():
        logger.error("Input directory not found: %s", input_dir)
        sys.exit(1)

    paso6 = _load_paso6()
    groups = _discover_pm_report_files(input_dir)

    if not groups:
        logger.error("No pm_report chunk files found in %s", input_dir)
        sys.exit(1)

    # Filter by --countries if provided
    if args.countries:
        wanted_iso = {c.strip().upper() for c in args.countries}
        groups = {k: v for k, v in groups.items() if k[0] in wanted_iso}
        if not groups:
            logger.error("None of the requested countries found in pm_report files")
            sys.exit(1)

    logger.info("Markets to process (%d groups): %s", len(groups), sorted(k[0] for k in groups))

    errors: List[str] = []
    for (iso, ts), paths in sorted(groups.items()):
        slug = ISO_TO_SLUG.get(iso, iso.lower())
        try:
            process_market(iso, ts, paths, paso6, args.dry_run)
        except Exception as exc:
            logger.error("[%s] FAILED: %s", slug, exc, exc_info=True)
            errors.append(slug)

    if errors:
        logger.warning("Failed/skipped countries: %s", errors)
        sys.exit(1)
    else:
        logger.info("All pm_report decision files processed successfully.")


if __name__ == "__main__":
    main()
